version: '3.9'
services:
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '6381:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_master_password
    volumes:
      - './docker-compose/redis-master:/bitnami'
    networks:
      - app-net
      - redis-net
    deploy:
      replicas: 1

  redis-slave:
    image: 'bitnami/redis:latest'
    volumes:
      - ./docker-compose/redis-slave:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=my_master_password
      - REDIS_PASSWORD=my_master_password
    ports:
      - '6379'
    depends_on:
      - redis-master
    # command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb --maxmemory-policy allkeys-lru
    networks:
      - redis-net
    deploy:
      replicas: 3

  mysql-master:
    image: bitnami/mysql:latest
    ports:
      - '5665:3306'
    # command: --init-file /data/application/init.sql
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      # - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=my_root_password
      - MYSQL_DATABASE=sf341
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_user_password
    volumes:
      # - './init.sql:/data/application/init.sql'
      # - './init.sql:/docker-entrypoint-startdb.d/init.sql'
      - './docker-compose/mysql:/bitnami/mysql/data'

    networks:
      - mysql-net

    deploy:
      replicas: 1

  mysql-slave:
    image: 'bitnami/mysql:latest'
    ports:
      - '3306'
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user

      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=my_root_password
    networks:
      - mysql-net
    deploy:
      replicas: 2

networks:
  app-net:
    driver: bridge

  mongodb-net:
    driver: bridge

  redis-net:
    driver: bridge
  mysql-net:
    driver: bridge
