version: '3'

services:
  redis:
    image: redis:latest
    container_name: master
    ports:
      - "10000:6379"
    networks:
      - redis-replication

  redis-slave:
    image: redis:latest
    # container_name: slave
    ports:
      - "6379"
    command: redis-server --slaveof master 6379
    depends_on:
      - redis
    networks:
      - redis-replication
    deploy:
      replicas: 2
    

networks:
  redis-replication:
    driver: bridge
